### ISSUE TITLE
Release 2.0.9 Tracking Ticket

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1135]
### Is your feature request related to a problem?

Tracking Ticket for Release 2.0.9 Features/Issues

- [ ] [Frames Glow up](https://github.com/ephemeraHQ/converse-app/issues/1020)
- [ ] [Deep link/Notification Link Consistency](https://github.com/ephemeraHQ/converse-app/issues/1130)
- [ ] [V3 Split](https://github.com/ephemeraHQ/converse-app/issues/1134)
