### ISSUE TITLE
Bug: V3 Only Bug Tracking & Cleanup

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1259]
### Describe the bug

- [ ] Chat Screen content and header are mismatched
- [ ] Swipe to mark as unread is too sensitive (should have to go farther
- [ ] Creating a new DM and sending messages messages are not streamed
- [ ] DM Header Flashes Empty Profile When Navigating the first time
- [ ] Clicking Send a Message Does not dismiss the profile screen
- [ ] Turn on Notifications shows when already on
- [ ] Self Profile is delayed (Migrate to queries)
- [ ] Reply Message is the wrong color in dark mode
- [ ] Debounce Search should display loading first
- [ ] Don't dismiss Splash screen until persisted conversation list is loaded
