### ISSUE TITLE
Identity Milestone Tracking Issue

### ISSUE THREAD

**Issue by alexrisch** [ephemeraHQ/converse-app#1301]
# Tracking issue for Identity Milestone

## Getting Started

Read the Approvals Write Up: https://www.notion.so/ephemerahq/Approvals-in-Converse-0ca3419d992c4acb853654b808a338ff
This is driving our decisions for what we want accounts to be able to do, money on ramps, etc.

Watch the latest loom on onboarding, and first time experience: https://www.loom.com/share/7f467f5fab0245e6897d39f31b8ec69f?sid=314bbe3f-5be4-4482-aa77-cd30212501cd
Not everything from this will be included in this current milestone, but we want to be setting out the foundation for it

Watch adding on chain identities: https://www.loom.com/share/7fb32960fe2c40b4a737907210595e9c

### Core Features Part 1:
- [x] #1359
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1298
- [x] #1374
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1296
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1297
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1259

### Core Features Part 2:
- [ ] #1360
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1263
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1295
- [ ] #1376
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1300
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1304
- [ ] #1361

### Core Features Part 3:
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1303

### Nice to Haves - Repo Health:
- [ ] https://github.com/ephemeraHQ/converse-app/issues/953
- [ ] https://github.com/ephemeraHQ/converse-app/issues/753

### Additional UX Improvements:
- [ ] https://github.com/ephemeraHQ/converse-app/issues/967
- [ ] https://github.com/ephemeraHQ/converse-app/issues/990
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1160

### Bugs
- [ ] https://github.com/ephemeraHQ/converse-app/issues/1312

**Comment by technoplato** [comment]
@nplasterer kill?
