### ISSUE TITLE
Tracking: Launch production network TestFlight

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#199]
Must have
- [x] v2 streaming complete
- [x] https://github.com/xmtp/libxmtp/pull/882
- [x] group description metadata binding
- [x] group consent
- [ ] TestFlight group: `Ephemera-Int`
- [ ] Google group for Android alpha: `Ephemera-Int`
- [ ] Wallet connection and signature flow tested

Nice to have
- [x] https://github.com/xmtp/libxmtp/issues/881
