### ISSUE TITLE
Tracking - Groups MVP

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#25]
### Outstanding basic operations

- [x] #75 
- [x] #76

### UX
*Migrated from [Notion](https://www.notion.so/xmtplabs/Group-Chat-EthCC-Tracking-Issue-ac36951fff6e403f9c006a2013d49dbc?pvs=4)*

- [x] #22
- [x]  **Screen: Create new group** 
    - [x] #30
    - [x]  Add initial group description
    - [x] #94
        - [x] #93
    - [x] Add members
        - [x]  Search for member
     - [x] #32
- [x]  **Screen: Group member detail***
    - [x]  Send message
    - [x]  Block member for me
    - [x]  Unblock member for me
    - [x]  Permitted admin actions
        - [x] #37
        - [x] #38
        - [x] #39
- [x]  **Screen: Member list**
    - [x]  Superadmin view
        - [x]  Promote new admin
        - [x]  Demote admin
    - [x]  Admin view
        - [x]  Remove member
        - [ ] #932
        - [ ]  Unmute member globally
    - [x]  Member view
        - [x]  View member profile
 - [x]  **Screen: Add member to existing group**
    - [x]  Search for member
- [x]  **Screen: Group Requests**
    - [x]  Accept group invite
    - [x]  Reject group invite
    - [x]  Block sender
- [x]  **Screen: Group Details**
    - [x]  Invite enablement
        - [x]  QR code
        - [x]  Create invite link
     - [x]  Admin settings
        - [x]  Change image
        - [x]  Change description
        - [x]  Change group name
     - [ ]  Member settings
        - [ ] #931
        - [ ]  Toggle push notifications

### Visual updates
- [x] #69 
- [x] #71 
- [x] #74 

### UX
- [ ] [Admins] Pinned messages
- [ ] [Create group] [Group detail] Select NFT for group image
- [ ] [Superadmins] [Member list] [Member detail] Promote member to admin
- [ ] [Superadmins] [Member list] [ Member detail] Demote admin to member
- [ ] [Member list] [Member detail] Block member
- [ ] [Member list] [Member detail] Unblock member
- [ ] [Group detail] Gallery of frames shared by group members
- [ ] [Group detail] Gallery of tokens shared by group members
