### ISSUE TITLE
(Rollup) Sender name/address/inboxId issues

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#443]
```[tasklist]
### Tasks
- [ ] https://github.com/ephemeraHQ/converse-app/issues/392
- [ ] https://github.com/ephemeraHQ/converse-app/issues/433
- [ ] https://github.com/ephemeraHQ/converse-app/issues/134
- [ ] https://github.com/ephemeraHQ/converse-app/issues/441
- [ ] https://github.com/ephemeraHQ/converse-app/issues/393
- [ ] https://github.com/ephemeraHQ/converse-app/issues/431
- [ ] https://github.com/ephemeraHQ/converse-app/issues/435
- [ ] https://github.com/ephemeraHQ/converse-app/issues/358
- [ ] https://github.com/ephemeraHQ/converse-app/issues/399
```
