### ISSUE TITLE
Tracking: Performance & Architecture

### ISSUE THREAD

**Issue by nplasterer** [ephemeraHQ/converse-app#504]
- [ ] quick scrolling on conversation list view shows blank spaces
- [ ] react hooks called too many times when it’s not necessary (useless rerenders)
- [ ] initial loading time of the app (loading the sqlite db data into the app state, while the splash screen is shown)
- [ ] initial sync (while the activity indicator is shown) time improvement (when we only use v3 so when 1:1 has been migrated)
- [ ] overlapping messages, jumpy scroll & flash list improvements (long list of items of varying height
- [ ] overall perf, especially on older android devices, due to RN (try the [new architecture](https://docs.expo.dev/guides/new-architecture/) in the next Expo version and see what breaks)
- [ ] message cell rendering performance (including regex to parse content / unfurl frames)
- [x] #807
