### ISSUE TITLE
Tracking: Polished UX

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#509]
```[tasklist]
### Bugs
- [ ] https://github.com/ephemeraHQ/converse-app/issues/333
- [ ] https://github.com/ephemeraHQ/converse-app/issues/726
- [ ] https://github.com/ephemeraHQ/converse-app/issues/341
- [ ] https://github.com/ephemeraHQ/converse-app/issues/604
- [ ] https://github.com/ephemeraHQ/converse-app/issues/589
- [ ] https://github.com/ephemeraHQ/converse-app/issues/608
- [ ] https://github.com/ephemeraHQ/converse-app/issues/610
- [ ] https://github.com/ephemeraHQ/converse-app/issues/809
- [ ] https://github.com/ephemeraHQ/converse-app/issues/767
- [ ] https://github.com/ephemeraHQ/converse-app/issues/723
- [ ] https://github.com/ephemeraHQ/converse-app/issues/667
- [ ] https://github.com/ephemeraHQ/converse-app/issues/640
- [ ] https://github.com/ephemeraHQ/converse-app/issues/623
- [ ] https://github.com/ephemeraHQ/converse-app/issues/334
- [ ] https://github.com/ephemeraHQ/converse-app/issues/429
- [ ] https://github.com/ephemeraHQ/converse-app/issues/330
- [ ] https://github.com/ephemeraHQ/converse-app/issues/346
- [ ] https://github.com/ephemeraHQ/converse-app/issues/295
- [ ] https://github.com/ephemeraHQ/converse-app/issues/331
- [ ] https://github.com/ephemeraHQ/converse-app/issues/609
- [ ] https://github.com/ephemeraHQ/converse-app/issues/592
```

```[tasklist]
### Ready
- [ ] https://github.com/ephemeraHQ/converse-app/issues/286
- [ ] https://github.com/ephemeraHQ/converse-app/issues/758
- [ ] https://github.com/ephemeraHQ/converse-app/issues/729
- [ ] https://github.com/ephemeraHQ/converse-app/issues/810
- [ ] https://github.com/ephemeraHQ/converse-app/issues/811
- [ ] https://github.com/ephemeraHQ/converse-app/issues/727
- [ ] https://github.com/ephemeraHQ/converse-app/issues/142
- [ ] https://github.com/ephemeraHQ/converse-app/issues/571
- [ ] https://github.com/ephemeraHQ/converse-app/issues/427
- [ ] https://github.com/ephemeraHQ/converse-app/issues/597
- [ ] https://github.com/ephemeraHQ/converse-app/issues/596
- [ ] https://github.com/ephemeraHQ/converse-app/issues/315
- [ ] https://github.com/ephemeraHQ/converse-app/issues/178
- [ ] https://github.com/ephemeraHQ/converse-app/issues/572
- [ ] https://github.com/ephemeraHQ/converse-app/issues/581
```

```[tasklist]
### Needs Product/Design
- [ ] https://github.com/ephemeraHQ/converse-app/issues/428
- [ ] https://github.com/ephemeraHQ/converse-app/issues/182
- [ ] https://github.com/ephemeraHQ/converse-app/issues/557
- [ ] https://github.com/ephemeraHQ/converse-app/issues/177
- [ ] https://github.com/ephemeraHQ/converse-app/issues/224
- [ ] https://github.com/ephemeraHQ/converse-app/issues/162
- [ ] https://github.com/ephemeraHQ/converse-app/issues/159
- [ ] https://github.com/ephemeraHQ/converse-app/issues/61
- [ ] https://github.com/ephemeraHQ/converse-app/issues/742
- [ ] https://github.com/ephemeraHQ/converse-app/issues/757
- [ ] https://github.com/ephemeraHQ/converse-app/issues/659
- [ ] New Conversation flow: improved UX for adding group members, styles
- [ ] Allow/block module buttons, styles, copy
- [ ] Matchmaker data (presentation template, not actual data)
- [ ] Profile page needs styles/copy pass
- [ ] Spacing and sizing pass for all screens
- [ ] Light icons pass
- [ ] Reply composer: style like Messenger
- [ ] Conversation list swipe actions
- [ ] Light animations pass
- [ ] Audit error states
```
