### ISSUE TITLE
Tracking: 9/1 Release

### ISSUE THREAD

**Issue by saulmc** [ephemeraHQ/converse-app#570]
```[tasklist]
### Tasks
- [ ] https://github.com/ephemeraHQ/converse-app/issues/412
- [ ] https://github.com/ephemeraHQ/converse-app/issues/567
- [ ] https://github.com/ephemeraHQ/converse-app/issues/571
- [ ] https://github.com/ephemeraHQ/converse-app/issues/572
- [ ] https://github.com/ephemeraHQ/converse-app/issues/315
- [ ] https://github.com/ephemeraHQ/converse-app/issues/514
- [ ] https://github.com/ephemeraHQ/converse-app/issues/346
- [ ] https://github.com/ephemeraHQ/converse-app/pull/569
- [ ] https://github.com/ephemeraHQ/converse-app/issues/563
- [ ] https://github.com/ephemeraHQ/converse-app/issues/556
- [ ] https://github.com/ephemeraHQ/converse-app/issues/330
- [ ] https://github.com/ephemeraHQ/converse-app/issues/348
- [ ] https://github.com/ephemeraHQ/converse-app/issues/368
- [ ] https://github.com/ephemeraHQ/converse-app/issues/581
- [ ] https://github.com/ephemeraHQ/converse-app/issues/597
- [ ] https://github.com/ephemeraHQ/converse-app/issues/620
```
